export const tickers = {
  results: [
    {
      ticker: 'A',
      name: 'Agilent Technologies Inc.',
      market: 'stocks',
      locale: 'us',
      primary_exchange: 'XNYS',
      type: 'CS',
      active: true,
      currency_name: 'usd',
      cik: '0001090872',
      composite_figi: 'BBG000BWQYZ5',
      share_class_figi: 'BBG001SCTQY4',
      last_updated_utc: '2021-08-25T00:00:00Z',
    },
    {
      ticker: 'AA',
      name: 'Alcoa Corporation',
      market: 'stocks',
      locale: 'us',
      primary_exchange: 'XNYS',
      type: 'CS',
      active: true,
      currency_name: 'usd',
      cik: '0001675149',
      composite_figi: 'BBG00B3T3HD3',
      share_class_figi: 'BBG00B3T3HF1',
      last_updated_utc: '2021-08-25T00:00:00Z',
    },
    {
      ticker: 'AAA',
      name: 'AAF First Priority CLO Bond ETF',
      market: 'stocks',
      locale: 'us',
      primary_exchange: 'ARCX',
      type: 'ETF',
      active: true,
      currency_name: 'usd',
      composite_figi: 'BBG00X5FSP48',
      share_class_figi: 'BBG00X5FSPZ4',
      last_updated_utc: '2021-08-25T00:00:00Z',
    },
    {
      ticker: 'AAAU',
      name: 'Goldman Sachs Physical Gold ETF Shares',
      market: 'stocks',
      locale: 'us',
      primary_exchange: 'ARCX',
      active: true,
      currency_name: 'usd',
      cik: '0001708646',
      composite_figi: 'BBG00LPXX872',
      share_class_figi: 'BBG00LPXX8Z1',
      last_updated_utc: '2021-08-25T00:00:00Z',
    },
    {
      ticker: 'AAC',
      name: 'Ares Acquisition Corporation',
      market: 'stocks',
      locale: 'us',
      primary_exchange: 'XNYS',
      type: 'CS',
      active: true,
      currency_name: 'usd',
      cik: '0001829432',
      last_updated_utc: '2021-08-25T00:00:00Z',
    },
    {
      ticker: 'AAC.U',
      name: 'Ares Acquisition Corporation Units, each consisting of one Class A ordinary share, and one-fifth of',
      market: 'stocks',
      locale: 'us',
      primary_exchange: 'XNYS',
      type: 'UNIT',
      active: true,
      currency_name: 'usd',
      cik: '0001829432',
      last_updated_utc: '2021-08-25T00:00:00Z',
    },
    {
      ticker: 'AAC.WS',
      name: 'Ares Acquisition Corporation Redeemable Warrants, each whole warrant exercisable for one Class A ord',
      market: 'stocks',
      locale: 'us',
      primary_exchange: 'XNYS',
      type: 'WARRANT',
      active: true,
      currency_name: 'usd',
      cik: '0001829432',
      last_updated_utc: '2021-08-25T00:00:00Z',
    },
    {
      ticker: 'AACG',
      name: 'ATA Creativity Global American Depositary Shares',
      market: 'stocks',
      locale: 'us',
      primary_exchange: 'XNAS',
      type: 'ADRC',
      active: true,
      currency_name: 'usd',
      cik: '0001420529',
      composite_figi: 'BBG000V2S3P6',
      share_class_figi: 'BBG001T125S9',
      last_updated_utc: '2021-08-25T00:00:00Z',
    },
    {
      ticker: 'AACIU',
      name: 'Armada Acquisition Corp. I Unit',
      market: 'stocks',
      locale: 'us',
      primary_exchange: 'XNAS',
      type: 'UNIT',
      active: true,
      currency_name: 'usd',
      cik: '0001844817',
      composite_figi: 'BBG011PFP1D1',
      share_class_figi: 'BBG011PFP285',
      last_updated_utc: '2021-08-25T00:00:00Z',
    },
    {
      ticker: 'AADR',
      name: 'AdvisorShares Dorsey Wright ADR ETF',
      market: 'stocks',
      locale: 'us',
      primary_exchange: 'XNAS',
      type: 'ETF',
      active: true,
      currency_name: 'usd',
      cik: '0001408970',
      composite_figi: 'BBG000BDYRW6',
      share_class_figi: 'BBG001T9B1Y4',
      last_updated_utc: '2021-08-25T00:00:00Z',
    },
  ],
  status: 'OK',
  request_id: 'c27c45c64c70422b53bd4ee260fc9ed1',
  count: 10,
  next_url:
    'https://api.polygon.io/v3/reference/tickers?cursor=YWN0aXZlPXRydWUmZGF0ZT0yMDIxLTA4LTI1JmxpbWl0PTEwJm9yZGVyPWFzYyZwYWdlX21hcmtlcj1BQURSJTdDYTQ0ZWMzMDlmMDk0ZmNlNjEwMGI5YTg2YjVmZmVkMGY2YmIzYzE2MTQzMmI0ZWRmNTk1YjVhMGJhNDYxMGQ3MCZzb3J0PXRpY2tlcg',
};
